name: useful_app
description: A usefulapp

version: 1.5.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  adaptive_theme: 3.1.1
  shared_preferences: ^2.0.16
  package_info_plus:
  cupertino_icons: ^1.0.2
  settings_ui: ^2.0.2
  intl: ^0.17.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/fruit.png
